### ISSUE TITLE
Ignore excluded files, and support linkgroups

### ISSUE THREAD

**Issue by davebranton** [jimon/premake-ninja#17]
I've fixed both the above issues locally, but this project seems dead.

Is it still alive, but just moving very slowly?

**Comment by jimon** [comment]
Yes, I don't have time/interest to maintain it right now.

If someone wants to take over maintenance I'm willing to transfer the project :)

**Comment by Jarod42** [comment]
I might be interested. :-)

**Comment by jimon** [comment]
@Jarod42 I'm adding you as a collaborator, feel free to have fun with the code :) would be lovely to get some sort of traction going

**Comment by Jarod42** [comment]
`linkgroupss` fixed by https://github.com/jimon/premake-ninja/commit/b69282508b12df528f54a37d91cbe39200872960
