### ISSUE TITLE
Issues with including other premake files

### ISSUE THREAD

**Issue by szammyboi** [jimon/premake-ninja#21]
I want to split my different projects up into their own independent premake files and then include them into the master premake file with the workspace established. It compiles perfectly fine in premake but the ninja build commands never actually build anything from the other project files. Is this not supported yet or am I doing something wrong?

**Comment by szammyboi** [comment]
Fixed with @annagrram pull request

**Comment by Jarod42** [comment]
To close with #19

**Comment by Jarod42** [comment]
Should be fixed by https://github.com/jimon/premake-ninja/commit/5729cbe78dbe0d6994d4c06a0c7f6cbbda68dcd9
