### ISSUE TITLE
ninja: error: multiple rules generate bin/converter/Converter

### ISSUE THREAD

**Issue by Cpt-Squirrell** [jimon/premake-ninja#22]
I am completely new to premake (after giving up all hope over CMake) but this `premake5.lua` file generates a make file with no questions asked. It spits out the error in title when used with ninja. Am I doing something wrong or is it wrong?
```
workspace "TBTED"
    configurations { "Debug", "Release" }
    kind "ConsoleApp"
    language "C++"
    targetdir "bin"

project "Converter"
    targetdir "bin/converter"
    files { "converter.cpp" }

    filter "configurations:Debug"
        defines { "_DEBUG_" }
```

(At the same time I will also ask on the side here if it's intentional for ninja to have a seperate file for each configuration (premake generates three files). ~~Make only requires a single makefile, does Ninja require multiple?~~ My bad, make does use multiple files.)

**Comment by Jarod42** [comment]
Issue is that both Debug and Release would generate "bin/converter/Converter.exe".
You either need to generate in different location (as `targetdir "bin/%{cfg.buildcfg}/converter"`) or have different output name (`targetname "Converter_%{cfg.buildcfg}")`.

Normally, now, warning/error for duplicate entries should be shown from premake call, and extra rule skipped.
