### ISSUE TITLE
Does not work with x64

### ISSUE THREAD

**Issue by p0358** [jimon/premake-ninja#26]
To repro, add this to one of test projects:
```
architecture "x86_64"
platforms "x64"
```
Result:
```
Building configurations...
Running action 'ninja'...
Generated build/build.ninja...
Generated build/build_ninjatestprj_debug_x64.ninja...
Generated build/build_ninjatestprj_release_x64.ninja...
Done (40ms).
ninja: error: 'ninjatestprj_debug_x64' missing and no known rule to make it
```

The issue is that a file like `build_ninjatestprj_release_x64.ninja` will be created, but in its line is `build ninjatestprj_release` without _x64.

I think the _x64 should be included (cause x86 variant can exist), especially that architecture is often also reflected in the target path (such as `x64/Release`) in build configs.

I'm making issue rather than PR as currently I'm not too sure how to fix it...

**Comment by Jarod42** [comment]
Duplicate #9, no?

**Comment by p0358** [comment]
Oh that might be, I didn't notice the other issue

**Comment by Jarod42** [comment]
Fixed by https://github.com/jimon/premake-ninja/commit/699a87a6b8c7a006bc47de03bcd5d3314b465498
